// Mocks generated by Mockito 5.4.6 from annotations
// in jup/test/features/surveys/controllers/survey_create_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i8;

import 'package:http/http.dart' as _i2;
import 'package:jup/features/surveys/controllers/surveys_controller.dart'
    as _i9;
import 'package:jup/features/surveys/models/custom_option_model.dart' as _i4;
import 'package:jup/features/surveys/models/survey_model.dart' as _i3;
import 'package:jup/shared/models/comment_model.dart' as _i10;
import 'package:jup/shared/services/api_client.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSurveyEntry_1 extends _i1.SmartFake implements _i3.SurveyEntry {
  _FakeSurveyEntry_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomOption_2 extends _i1.SmartFake implements _i4.CustomOption {
  _FakeCustomOption_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StrapiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStrapiClient extends _i1.Mock implements _i5.StrapiClient {
  MockStrapiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i7.Future<_i2.Response> get(
    String? path, {
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParams: queryParams, #useUserAuth: useUserAuth},
            ),
            returnValue: _i7.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParams: queryParams, #useUserAuth: useUserAuth},
                ),
              ),
            ),
          )
          as _i7.Future<_i2.Response>);

  @override
  _i7.Future<_i2.Response> post(
    String? path, {
    Object? body,
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #body: body,
                #queryParams: queryParams,
                #useUserAuth: useUserAuth,
              },
            ),
            returnValue: _i7.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #queryParams: queryParams,
                    #useUserAuth: useUserAuth,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.Response>);

  @override
  _i7.Future<_i2.Response> put(
    String? path, {
    Object? body,
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #body: body,
                #queryParams: queryParams,
                #useUserAuth: useUserAuth,
              },
            ),
            returnValue: _i7.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #body: body,
                    #queryParams: queryParams,
                    #useUserAuth: useUserAuth,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.Response>);

  @override
  _i7.Future<int> uploadFile(String? filePath, {bool? useUserAuth = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [filePath],
              {#useUserAuth: useUserAuth},
            ),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>> postMultipartWithMedia(
    String? path, {
    required Map<String, dynamic>? data,
    _i8.File? heroImage,
    List<_i8.File>? blockMedia = const [],
    bool? useUserAuth = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postMultipartWithMedia,
              [path],
              {
                #data: data,
                #heroImage: heroImage,
                #blockMedia: blockMedia,
                #useUserAuth: useUserAuth,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i2.Response> delete(String? path, {bool? useUserAuth = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path], {#useUserAuth: useUserAuth}),
            returnValue: _i7.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#delete, [path], {#useUserAuth: useUserAuth}),
              ),
            ),
          )
          as _i7.Future<_i2.Response>);

  @override
  List<dynamic> parseListResponse(
    _i2.Response? response, {
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseListResponse,
              [response],
              {#errorMessage: errorMessage},
            ),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Map<String, dynamic> parseSingleResponse(
    _i2.Response? response, {
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseSingleResponse,
              [response],
              {#errorMessage: errorMessage},
            ),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void assertSuccess(_i2.Response? response, {String? errorMessage}) =>
      super.noSuchMethod(
        Invocation.method(
          #assertSuccess,
          [response],
          {#errorMessage: errorMessage},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SurveysController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurveysController extends _i1.Mock implements _i9.SurveysController {
  MockSurveysController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.SurveyEntry>> fetchSurveys({
    int? pageSize = 25,
    int? page = 1,
    _i3.SurveyType? type,
    bool? activeOnly = false,
    String? groupDocumentId,
    bool? globalOnly = false,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSurveys, [], {
              #pageSize: pageSize,
              #page: page,
              #type: type,
              #activeOnly: activeOnly,
              #groupDocumentId: groupDocumentId,
              #globalOnly: globalOnly,
              #useUserAuth: useUserAuth,
            }),
            returnValue: _i7.Future<List<_i3.SurveyEntry>>.value(
              <_i3.SurveyEntry>[],
            ),
          )
          as _i7.Future<List<_i3.SurveyEntry>>);

  @override
  _i7.Future<_i3.SurveyEntry> fetchSurveyById(
    String? documentId, {
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchSurveyById,
              [documentId],
              {#useUserAuth: useUserAuth},
            ),
            returnValue: _i7.Future<_i3.SurveyEntry>.value(
              _FakeSurveyEntry_1(
                this,
                Invocation.method(
                  #fetchSurveyById,
                  [documentId],
                  {#useUserAuth: useUserAuth},
                ),
              ),
            ),
          )
          as _i7.Future<_i3.SurveyEntry>);

  @override
  _i7.Future<_i3.SurveyEntry> voteOnElectionSurvey(
    String? surveyDocumentId,
    int? userId,
    String? optionText,
    List<_i3.SurveyOption>? currentOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#voteOnElectionSurvey, [
              surveyDocumentId,
              userId,
              optionText,
              currentOptions,
            ]),
            returnValue: _i7.Future<_i3.SurveyEntry>.value(
              _FakeSurveyEntry_1(
                this,
                Invocation.method(#voteOnElectionSurvey, [
                  surveyDocumentId,
                  userId,
                  optionText,
                  currentOptions,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.SurveyEntry>);

  @override
  _i7.Future<_i3.SurveyEntry> voteOnSurvey(
    String? surveyDocumentId,
    int? userId,
    String? optionText,
    List<_i3.SurveyOption>? currentOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#voteOnSurvey, [
              surveyDocumentId,
              userId,
              optionText,
              currentOptions,
            ]),
            returnValue: _i7.Future<_i3.SurveyEntry>.value(
              _FakeSurveyEntry_1(
                this,
                Invocation.method(#voteOnSurvey, [
                  surveyDocumentId,
                  userId,
                  optionText,
                  currentOptions,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.SurveyEntry>);

  @override
  _i7.Future<_i3.SurveyEntry> voteOnPoll(
    String? surveyDocumentId,
    int? userId,
    bool? voteYes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#voteOnPoll, [surveyDocumentId, userId, voteYes]),
            returnValue: _i7.Future<_i3.SurveyEntry>.value(
              _FakeSurveyEntry_1(
                this,
                Invocation.method(#voteOnPoll, [
                  surveyDocumentId,
                  userId,
                  voteYes,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.SurveyEntry>);

  @override
  _i7.Future<_i3.SurveyEntry> addComment(
    String? surveyDocumentId,
    String? text,
    int? userId,
    List<_i10.Comment>? currentComments,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [
              surveyDocumentId,
              text,
              userId,
              currentComments,
            ]),
            returnValue: _i7.Future<_i3.SurveyEntry>.value(
              _FakeSurveyEntry_1(
                this,
                Invocation.method(#addComment, [
                  surveyDocumentId,
                  text,
                  userId,
                  currentComments,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.SurveyEntry>);

  @override
  _i7.Future<_i4.CustomOption> submitCustomOption(
    String? surveyDocumentId,
    String? text,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitCustomOption, [surveyDocumentId, text]),
            returnValue: _i7.Future<_i4.CustomOption>.value(
              _FakeCustomOption_2(
                this,
                Invocation.method(#submitCustomOption, [
                  surveyDocumentId,
                  text,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.CustomOption>);

  @override
  _i7.Future<List<_i4.CustomOption>> fetchMyCustomOptions(
    String? surveyDocumentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyCustomOptions, [surveyDocumentId]),
            returnValue: _i7.Future<List<_i4.CustomOption>>.value(
              <_i4.CustomOption>[],
            ),
          )
          as _i7.Future<List<_i4.CustomOption>>);

  @override
  _i7.Future<_i4.CustomOption> approveCustomOption(
    String? customOptionDocumentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#approveCustomOption, [customOptionDocumentId]),
            returnValue: _i7.Future<_i4.CustomOption>.value(
              _FakeCustomOption_2(
                this,
                Invocation.method(#approveCustomOption, [
                  customOptionDocumentId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.CustomOption>);

  @override
  _i7.Future<_i4.CustomOption> rejectCustomOption(
    String? customOptionDocumentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rejectCustomOption, [customOptionDocumentId]),
            returnValue: _i7.Future<_i4.CustomOption>.value(
              _FakeCustomOption_2(
                this,
                Invocation.method(#rejectCustomOption, [
                  customOptionDocumentId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.CustomOption>);

  @override
  _i7.Future<_i4.CustomOption> undoCustomOptionReview(
    String? customOptionDocumentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#undoCustomOptionReview, [
              customOptionDocumentId,
            ]),
            returnValue: _i7.Future<_i4.CustomOption>.value(
              _FakeCustomOption_2(
                this,
                Invocation.method(#undoCustomOptionReview, [
                  customOptionDocumentId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.CustomOption>);

  @override
  _i7.Future<_i4.CustomOption> voteOnCustomOption(
    String? customOptionDocumentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#voteOnCustomOption, [customOptionDocumentId]),
            returnValue: _i7.Future<_i4.CustomOption>.value(
              _FakeCustomOption_2(
                this,
                Invocation.method(#voteOnCustomOption, [
                  customOptionDocumentId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.CustomOption>);

  @override
  _i7.Future<_i3.SurveyEntry> deleteComment(
    String? surveyDocumentId,
    int? commentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [surveyDocumentId, commentId]),
            returnValue: _i7.Future<_i3.SurveyEntry>.value(
              _FakeSurveyEntry_1(
                this,
                Invocation.method(#deleteComment, [
                  surveyDocumentId,
                  commentId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.SurveyEntry>);

  @override
  _i7.Future<void> incrementViewCount(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementViewCount, [documentId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
