// Mocks generated by Mockito 5.4.6 from annotations
// in jup/test/features/events/controllers/events_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:jup/shared/services/api_client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StrapiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStrapiClient extends _i1.Mock implements _i3.StrapiClient {
  MockStrapiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.Response> get(
    String? path, {
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParams: queryParams, #useUserAuth: useUserAuth},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParams: queryParams, #useUserAuth: useUserAuth},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> post(
    String? path, {
    Object? body,
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #body: body,
                #queryParams: queryParams,
                #useUserAuth: useUserAuth,
              },
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #queryParams: queryParams,
                    #useUserAuth: useUserAuth,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> put(
    String? path, {
    Object? body,
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #body: body,
                #queryParams: queryParams,
                #useUserAuth: useUserAuth,
              },
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #body: body,
                    #queryParams: queryParams,
                    #useUserAuth: useUserAuth,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> delete(String? path, {bool? useUserAuth = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path], {#useUserAuth: useUserAuth}),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#delete, [path], {#useUserAuth: useUserAuth}),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  List<dynamic> parseListResponse(
    _i2.Response? response, {
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseListResponse,
              [response],
              {#errorMessage: errorMessage},
            ),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Map<String, dynamic> parseSingleResponse(
    _i2.Response? response, {
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseSingleResponse,
              [response],
              {#errorMessage: errorMessage},
            ),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void assertSuccess(_i2.Response? response, {String? errorMessage}) =>
      super.noSuchMethod(
        Invocation.method(
          #assertSuccess,
          [response],
          {#errorMessage: errorMessage},
        ),
        returnValueForMissingStub: null,
      );
}
