// Mocks generated by Mockito 5.4.6 from annotations
// in jup/test/features/events/controllers/event_create_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i7;

import 'package:http/http.dart' as _i2;
import 'package:jup/features/events/controllers/events_controller.dart' as _i8;
import 'package:jup/features/events/models/event_model.dart' as _i3;
import 'package:jup/shared/models/comment_model.dart' as _i9;
import 'package:jup/shared/services/api_client.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventEntry_1 extends _i1.SmartFake implements _i3.EventEntry {
  _FakeEventEntry_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StrapiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStrapiClient extends _i1.Mock implements _i4.StrapiClient {
  MockStrapiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.Response> get(
    String? path, {
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParams: queryParams, #useUserAuth: useUserAuth},
            ),
            returnValue: _i6.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParams: queryParams, #useUserAuth: useUserAuth},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> post(
    String? path, {
    Object? body,
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #body: body,
                #queryParams: queryParams,
                #useUserAuth: useUserAuth,
              },
            ),
            returnValue: _i6.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #queryParams: queryParams,
                    #useUserAuth: useUserAuth,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> put(
    String? path, {
    Object? body,
    Map<String, String>? queryParams,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #body: body,
                #queryParams: queryParams,
                #useUserAuth: useUserAuth,
              },
            ),
            returnValue: _i6.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #body: body,
                    #queryParams: queryParams,
                    #useUserAuth: useUserAuth,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response>);

  @override
  _i6.Future<int> uploadFile(String? filePath, {bool? useUserAuth = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [filePath],
              {#useUserAuth: useUserAuth},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<Map<String, dynamic>> postMultipartWithMedia(
    String? path, {
    required Map<String, dynamic>? data,
    _i7.File? heroImage,
    List<_i7.File>? blockMedia = const [],
    bool? useUserAuth = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postMultipartWithMedia,
              [path],
              {
                #data: data,
                #heroImage: heroImage,
                #blockMedia: blockMedia,
                #useUserAuth: useUserAuth,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i2.Response> delete(String? path, {bool? useUserAuth = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path], {#useUserAuth: useUserAuth}),
            returnValue: _i6.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#delete, [path], {#useUserAuth: useUserAuth}),
              ),
            ),
          )
          as _i6.Future<_i2.Response>);

  @override
  List<dynamic> parseListResponse(
    _i2.Response? response, {
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseListResponse,
              [response],
              {#errorMessage: errorMessage},
            ),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Map<String, dynamic> parseSingleResponse(
    _i2.Response? response, {
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseSingleResponse,
              [response],
              {#errorMessage: errorMessage},
            ),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void assertSuccess(_i2.Response? response, {String? errorMessage}) =>
      super.noSuchMethod(
        Invocation.method(
          #assertSuccess,
          [response],
          {#errorMessage: errorMessage},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EventsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventsController extends _i1.Mock implements _i8.EventsController {
  MockEventsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.EventEntry>> fetchEvents({
    int? pageSize = 10,
    int? page = 1,
    Set<_i3.EventCategory>? categories,
    _i8.EventTimeFilter? timeFilter,
    String? groupDocumentId,
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEvents, [], {
              #pageSize: pageSize,
              #page: page,
              #categories: categories,
              #timeFilter: timeFilter,
              #groupDocumentId: groupDocumentId,
              #useUserAuth: useUserAuth,
            }),
            returnValue: _i6.Future<List<_i3.EventEntry>>.value(
              <_i3.EventEntry>[],
            ),
          )
          as _i6.Future<List<_i3.EventEntry>>);

  @override
  _i6.Future<_i3.EventEntry> fetchEventById(
    String? documentId, {
    bool? useUserAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [documentId],
              {#useUserAuth: useUserAuth},
            ),
            returnValue: _i6.Future<_i3.EventEntry>.value(
              _FakeEventEntry_1(
                this,
                Invocation.method(
                  #fetchEventById,
                  [documentId],
                  {#useUserAuth: useUserAuth},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.EventEntry>);

  @override
  _i6.Future<_i3.EventEntry> addParticipant(
    String? eventDocumentId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addParticipant, [eventDocumentId, userId]),
            returnValue: _i6.Future<_i3.EventEntry>.value(
              _FakeEventEntry_1(
                this,
                Invocation.method(#addParticipant, [eventDocumentId, userId]),
              ),
            ),
          )
          as _i6.Future<_i3.EventEntry>);

  @override
  _i6.Future<_i3.EventEntry> removeParticipant(
    String? eventDocumentId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipant, [eventDocumentId, userId]),
            returnValue: _i6.Future<_i3.EventEntry>.value(
              _FakeEventEntry_1(
                this,
                Invocation.method(#removeParticipant, [
                  eventDocumentId,
                  userId,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.EventEntry>);

  @override
  _i6.Future<void> addSavedEvent(int? userId, int? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#addSavedEvent, [userId, eventId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeSavedEvent(int? userId, int? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#removeSavedEvent, [userId, eventId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> incrementViewCount(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementViewCount, [documentId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.EventEntry> addComment(
    String? eventDocumentId,
    String? text,
    int? userId,
    List<_i9.Comment>? currentComments,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [
              eventDocumentId,
              text,
              userId,
              currentComments,
            ]),
            returnValue: _i6.Future<_i3.EventEntry>.value(
              _FakeEventEntry_1(
                this,
                Invocation.method(#addComment, [
                  eventDocumentId,
                  text,
                  userId,
                  currentComments,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.EventEntry>);

  @override
  _i6.Future<_i3.EventEntry> deleteComment(
    String? eventDocumentId,
    int? commentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [eventDocumentId, commentId]),
            returnValue: _i6.Future<_i3.EventEntry>.value(
              _FakeEventEntry_1(
                this,
                Invocation.method(#deleteComment, [eventDocumentId, commentId]),
              ),
            ),
          )
          as _i6.Future<_i3.EventEntry>);
}
